export const initialTasks = [
  {
    id: 1,
    phase: "V1",
    module: "Producto",
    title: "Definir visión del producto",
    description:
      "Documento corto explicando qué es Kanban IT Departament, para quién es y qué problema resuelve mejor que SPN.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 2,
    phase: "V1",
    module: "Arquitectura",
    title: "Elegir stack definitivo",
    description: "Confirmar Flutter + NestJS/FastAPI + PostgreSQL + Docker + storage privado.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 3,
    phase: "V1",
    module: "Seguridad",
    title: "Definir modelo de permisos",
    description:
      "Crear roles: Super Admin, Empresa Admin, RRHH, Supervisor, Empleado, Nómina y Auditor.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 4,
    phase: "V1",
    module: "Infraestructura",
    title: "Crear monorepo inicial",
    description: "Estructura apps/mobile, apps/admin, backend, docs e infra.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Bajo",
  },
  {
    id: 5,
    phase: "V1",
    module: "Diseño",
    title: "Crear prototipo Figma",
    description:
      "Diseñar login, dashboard empleado, solicitudes, documentos, empleados y panel RRHH.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 6,
    phase: "V2",
    module: "Auth",
    title: "Login seguro",
    description:
      "Implementar login con access token corto, refresh token rotativo y cierre de sesión.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 7,
    phase: "V2",
    module: "Auth",
    title: "MFA para administradores",
    description: "Agregar segundo factor para RRHH, Empresa Admin y Super Admin.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 8,
    phase: "V2",
    module: "Empresas",
    title: "Multi-tenant por company_id",
    description: "Todas las tablas sensibles deben separar datos por empresa desde el backend.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 9,
    phase: "V2",
    module: "Auditoría",
    title: "Audit logs base",
    description: "Registrar login, cambios de permisos, creación de usuarios y acciones críticas.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 10,
    phase: "V3",
    module: "Empleados",
    title: "CRUD de empleados",
    description:
      "Crear, editar, activar/desactivar empleados, departamentos, posiciones y datos básicos.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 11,
    phase: "V3",
    module: "Flutter",
    title: "Dashboard de empleado",
    description: "Pantalla con perfil, solicitudes, documentos, notificaciones y próximos eventos.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 12,
    phase: "V3",
    module: "Solicitudes",
    title: "Solicitudes de vacaciones",
    description: "Empleado solicita vacaciones, supervisor aprueba/rechaza y RRHH puede auditar.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 13,
    phase: "V3",
    module: "Solicitudes",
    title: "Licencias y permisos",
    description: "Flujo para licencia médica, permiso personal, ausencia y cambio de datos.",
    priority: "Media",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 14,
    phase: "V4",
    module: "Documentos",
    title: "Storage privado de documentos",
    description: "Subir documentos con permisos, URLs firmadas, expiración y logs de descarga.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 15,
    phase: "V4",
    module: "Documentos",
    title: "Generador de cartas laborales",
    description:
      "Plantillas PDF para carta laboral, certificación salarial y constancia de empleo.",
    priority: "Media",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 16,
    phase: "V5",
    module: "Reportes",
    title: "Dashboard RRHH",
    description:
      "Mostrar empleados activos, solicitudes pendientes, ausencias, documentos y actividad reciente.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 17,
    phase: "V5",
    module: "Notificaciones",
    title: "Notificaciones push/email",
    description:
      "Enviar alertas para aprobaciones, documentos, cambios de estado y tareas pendientes.",
    priority: "Media",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 18,
    phase: "V6",
    module: "Nómina",
    title: "Períodos de nómina",
    description: "Crear períodos, asignar empleados, ingresos, deducciones y cálculo neto inicial.",
    priority: "Media",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 19,
    phase: "V6",
    module: "Nómina",
    title: "Recibos de pago PDF",
    description: "Generar recibo de pago consultable desde app empleado y auditable por RRHH.",
    priority: "Media",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 20,
    phase: "V7",
    module: "Compliance RD",
    title: "Research TSS/DGII/DGT",
    description:
      "Documentar cálculos, reportes, formatos y responsabilidades legales en República Dominicana.",
    priority: "Alta",
    status: "Pendiente",
    effort: "Alto",
  },
  {
    id: 21,
    phase: "V8",
    module: "BI",
    title: "Métricas de ausentismo y headcount",
    description: "Crear gráficos por departamento, mes, tipo de ausencia y tendencia de empleados.",
    priority: "Baja",
    status: "Pendiente",
    effort: "Medio",
  },
  {
    id: 22,
    phase: "V8",
    module: "IA",
    title: "Asistente de RRHH futuro",
    description:
      "Explorar IA para resumir solicitudes, generar cartas y detectar patrones de ausencias.",
    priority: "Baja",
    status: "Pendiente",
    effort: "Alto",
  },
];
