export const defaultItConfig = {
  systems: ["Network", "Microsoft 365", "Active Directory", "Firewall", "Endpoints", "ERP"],
  ticketTypes: ["Incidente", "Cambio", "Mantenimiento", "Acceso", "Proyecto"],
  impacts: ["Bajo", "Medio", "Alto", "Crítico"],
  urgencies: ["Baja", "Media", "Alta", "Crítica"],
  team: ["IT Manager", "Soporte Nivel 1", "Infraestructura", "Mesa de ayuda"],
  jobTitles: [
    "IT Project Manager",
    "System Administrator",
    "Ciberseguridad",
    "DevOps Engineer",
    "Network Engineer",
    "Database Administrator",
    "Cloud Architect",
    "Soporte Técnico",
    "Help Desk Analyst",
    "IT Auditor",
  ],
  jobTitleHierarchy: {
    "IT Project Manager": "manager",
    "System Administrator": "admin",
    Ciberseguridad: "admin",
    "DevOps Engineer": "editor",
    "Network Engineer": "editor",
    "Database Administrator": "editor",
    "Cloud Architect": "editor",
    "Soporte Técnico": "viewer",
    "Help Desk Analyst": "viewer",
    "IT Auditor": "viewer",
  },
};
